version: '3.8'

services:
  redis:
    restart: always
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    hostname: redis.arefaste
    networks:
        - 1440-net
    volumes:
      - ./redis_doc/redis_data:/data

  postgres:
    restart: always
    build:
      context: ./postgres/
      dockerfile: Dockerfile
    container_name: postgres
    environment:
      POSTGRES_USER: service_tickets_1440
      POSTGRES_PASSWORD: i2TOOIMQxuz91c7Yc
      POSTGRES_DB: tickets_1440
    ports:
      - "5432:5432"
    hostname: postgres.arefaste
    networks:
        - 1440-net
    volumes:
      - ./postgres/pgdata:/var/lib/postgresql/data

  nginx:
    restart: always
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    hostname: nginx.arefaste
    networks:
        - 1440-net
    depends_on:
      - api

  api:
    restart: always
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: api
    environment:
      DATABASE_URL: postgresql://service_tickets_1440:i2TOOIMQxuz91c7Yc@postgres:5432/tickets_1440
      REDIS_URL: redis://redis:6379/0
      URL_AUTH: https://discord.com/oauth2/authorize?client_id=775047814911623179&response_type=code&redirect_uri=https%3A%2F%2F1440.arefaste.ru&scope=identify+guilds+email+connections
      CLIENT_ID: 775047814911623179
      CLIENT_SECRET: kHUES88yPuknC0Rrp0NVl8IMmHHqll2L
    hostname: api.arefaste
    networks:
        - 1440-net

    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis

  tickets_manager:
    build:
      context: ./tickets_manager
      dockerfile: Dockerfile
    container_name: tickets_manager
    environment:
      DATABASE_URL: postgresql://service_tickets_1440:i2TOOIMQxuz91c7Yc@postgres.arefaste:5432/tickets_1440
      REDIS_URL: redis://redis:6379/0
      CLIENT_ID: 775047814911623179
      CLIENT_SECRET: kHUES88yPuknC0Rrp0NVl8IMmHHqll2L
#      DATABASE_URL: postgresql://service_tickets_1440:i2TOOIMQxuz91c7Yc@localhost:5432/tickets_1440
      HOST_REDIS: redis.arefaste
      PWD_REDIS:
#      REDIS_URL: redis://redis:6379/0
      SECRET_CIPHER: SnNWSXFABs-nSHI0PZf5HI5yEz13Urx7M90WTOtbOcA=
      URL_AUTH: https://discord.com/oauth2/authorize?client_id=775047814911623179&response_type=code&redirect_uri=https%3A%2F%2F1440.arefaste.ru&scope=identify+guilds+email+connections
      REDIRECT_URI: https://1440.arefaste.ru
    hostname: tickets_manager.arefaste
    networks:
        - 1440-net
    depends_on:
      - redis

  tickets_notificator:
    build:
      context: ./tickets_notificator
      dockerfile: Dockerfile
    container_name: tickets_notificator
    environment:
      REDIS_URL: redis://redis:6379/0
    hostname: tickets_notificator.arefaste
    networks:
        - 1440-net
    depends_on:
      - redis

volumes:
  redis_data:
  postgres_data:


networks:
  1440-net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.169.34.0/24
          gateway: 192.169.34.1